import baseConfig from "../../eslint.config.mjs";

export default [
    ...baseConfig,
    {
        // Generated by `prisma generate`; never linted or hand-edited.
        ignores: ["src/generated/**"]
    }
];
